#!/bin/sh /etc/rc.common

START=58
USE_PROCD=1

init_board() {
    echo 15 > /sys/class/gpio/export
	echo low > /sys/class/gpio/gpio15/direction
	service=`uci get gateway.general.server_type`

	if [[ "$service" = "tcpudp" ]]; then
		process="tcp_client.lua"
	elif [[ "$service" = "mqtt" ]]; then
		process="mqtt_process.sh"
	elif [[ "$service" = "customized" ]]; then
		process=`uci get customized_script.general.script_name`
		ln /etc/lora/customized_scripts/$process /usr/bin/$process
	fi
}

start_service() {
    init_board
    procd_open_instance
    procd_set_param command /usr/bin/"$process"
    procd_set_param stdout 1
    procd_set_param respawn
    procd_set_param pidfile /var/run/"$process".pid
    procd_close_instance
}

reload_service() {
    stop
    start
}

service_triggers()
{
    procd_add_reload_trigger "network" "wireless" "gateway" "mqtt" "tcp_client" "customized_script"
}