#!/bin/sh /etc/rc.common

START=55
USE_PROCD=1

init_board() {

    board=`cat /var/iot/board`
    mode=`uci get gateway.general.server_type`

    if [[ "$board" = "LG02" ]]; then
        process="lg02_pkt_fwd"
    elif [[ "$board" = "LG01" ]]; then
        process="lg01_pkt_fwd"
    elif [[ "$board" = "LG08P" ]]; then
        process="lora_pkt_fwd"
        /usr/bin/reset_lgw.sh start
        /usr/bin/generate-config.sh
    elif [[ "$board" = "LG08" ]]; then
        process="lora_pkt_fwd"
        /usr/bin/reset_lgw.sh start
        /usr/bin/generate-config.sh
    else
        exit 1
    fi

    if [[ "$mode" = "disabled" ]]; then
        process_runing=`pidof $process`
        if [[ ! -z "process_runing" ]]; then
            stop
        fi
        exit 0
    fi

    DEB=`uci get gateway.general.DEB`
    if [[ "$DEB" -gt 1 ]]; then
        DEB="1"
    fi
}

start_service() {
    init_board
    procd_open_instance
    procd_set_param command /usr/bin/"$process"
    procd_set_param file  /etc/config/gateway
    procd_set_param stdout "$DEB"
    procd_set_param respawn
    procd_set_param pidfile /var/run/"$process".pid
    procd_close_instance
}

reload_service() {
    stop
    start
}

service_triggers()
{
    procd_add_reload_trigger "network" "wireless" "gateway" "mqtt" "tcp_client"
    for iface in `cat /etc/config/network | grep interface | awk -F "\'"  '{print $2}'`; do
        procd_add_interface_trigger "interface.*.up" "$iface" /etc/init.d/lora_gw reload
    done
}
