#!/bin/sh /etc/rc.common

START=18

start() {
	MODE=`/sbin/uci get wireless.@wifi-iface[0].mode`
	SSID=`/sbin/uci get wireless.@wifi-iface[0].ssid`
	SSID_PREFIX=`/sbin/uci get system.vendor.ssid_prefix`
	[ -z $SSID_PREFIX ] && SSID_PREFIX="Dragino"

	if [ "$MODE" == "ap" -a "$SSID" == "Arduino" ]
	then
		SSID_SUFFIX=`/sbin/ifconfig wlan0 | /usr/bin/head -n 1 | /bin/grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}' | /bin/sed 's/://g'`
		SSID="$SSID_PREFIX-$SSID_SUFFIX"
		/sbin/uci "set" "wireless.@wifi-iface[0].ssid=$SSID"
		/sbin/uci commit wireless
		logger -t rename "WiFi renamed $SSID"
	fi
}

