#!/bin/sh /etc/rc.common
# Copyright (c) 2014 Edwin Chen <edwin@dragino.com>

START=99
IOT_DIR='/etc/iot/scripts/'

start()
{
	#enable UART
	echo 24 > /sys/class/gpio/export
	echo "high" > /sys/class/gpio/gpio24/direction
	/etc/init.d/avahi-daemon restart
	/usr/bin/detect-avr
	/usr/bin/reset-mcu
	check_auto_update
	/usr/bin/iot-daemon &
	/usr/sbin/link_arduino_www.sh &
}

restart()
{
	/usr/bin/iot-daemon &
}

check_auto_update()
{
	# check if we need to do MCU auto update
	update_on_boot=`uci get sensor.auto_update.update_on_boot`
	if [ $update_on_boot = "1" ];then
		/usr/bin/auto-update-mcu.sh &
	fi 
}

