#!/bin/sh

#rename-hostname
uci set system.@system[0].key=$(hexdump -v -e '1/1 "%.2x"' -s $((0x100)) -n 16 /dev/mtd6)
uci set system.@system[0].device=$(hexdump -v -e '1/1 "%.2x"' -s $((0x120)) -n 16 /dev/mtd6)
hostname_prefix=$(uci get system.vendor.hostname)
uci set system.@system[0].hostname=$hostname_prefix-$(hexdump -v -e '1/1 "%.2x"' -s $((0x1005)) -n 3 /dev/mtd6)
echo $(uci get system.@system[0].hostname) > /proc/sys/kernel/hostname

rename_network_on_first_boot

uci add ucitrack secn
uci	set ucitrack.@secn[0].exec=/usr/bin/config_secn

uci add ucitrack gpstrack
uci	set ucitrack.@gpstrack[0].exec=/usr/bin/get_gpswox_api_hash.sh

uci add ucitrack gateway
uci	set ucitrack.@gateway[0].exec=/usr/bin/reset-gateway

uci	commit

exit 0
