/* confdefs.h */
#define PACKAGE_NAME "libmpsse"
#define PACKAGE_TARNAME "libmpsse"
#define PACKAGE_VERSION "1.3"
#define PACKAGE_STRING "libmpsse 1.3"
#define PACKAGE_BUGREPORT "http://libmpsse.googlecode.com"
#define PACKAGE_URL ""
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 1
#define HAVE_LIBFTDI1_FTDI_H 1
#define HAVE_LIBFTDI1 1
