#!/bin/sh /etc/rc.common

START=99
STOP=99
USE_PROCD=1

PROG="/usr/bin/helium_gateway"
CONFIG_DIR="/etc/helium_gateway/settings.toml"

init_board()
{
	gwcfg=`uci get gateway.general.gwcfg`
	cp /etc/helium_gateway/settings.toml.bak /etc/helium_gateway/settings.toml
	if [[ "$gwcfg"  = "EU" ]];then
		region="EU868"
	elif [[ "$gwcfg" = "US" ]];then
		region="US915"
	elif [[ "$gwcfg" = "AU" ]];then
		region="AU915_SB1"
	elif [[ "$gwcfg" = "CN" ]];then
		region="CN470"
	elif [[ "$gwcfg" = "IN" ]];then
		region="IN865"
	elif [[ "$gwcfg" = "RU" ]];then
		region="RU864"
	elif [[ "$gwcfg" = "AS1_2" ]] || [[ "$gwcfg" = "AS1" ]]; then
		region="AS923_1"
	elif [[ "$gwcfg" = "KR" ]];then
		region="KR920"
	elif [[ "$gwcfg" = "AS2" ]]; then
		region="AS923_2"
	elif [[ "$gwcfg" = "AS3" ]]; then
		region="AS923_3"
	elif [[ "$gwcfg" = "AS4" ]]; then
		region="AS923_4"
	fi
	
	sed -i "27 i\region = \"${region}\"" /etc/helium_gateway/settings.toml	
}

start_service() {
	init_board
	
    procd_open_instance

    procd_set_param command $PROG
    procd_append_param command -c $CONFIG_DIR server
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn

    procd_close_instance
}
