#!/bin/sh /etc/rc.common

START=50
STOP=90

start() {
    mkdir -p /var/iot/channels
    mkdir -p /var/iot/receive
	mkdir -p /var/iot/push

    rmmod gpio_keys_polled
    modprobe gpio_keys_polled

    rmmod spi-gpio-custom
    insmod spi-gpio-custom bus0=1,14,16,26,0,8000000,15 bus1=2,18,21,19,0,8000000,24
    sleep 1

    /usr/bin/spirw 8 0

    if [[ "$?" == "0" ]]; then
        echo "LG02" > /var/iot/board
    else 
        /usr/bin/spirw 23 1
        if [[ "$?" == "0" ]]; then
            echo "LG01" > /var/iot/board
        else
            rmmod spi-gpio-custom
            insmod spi-gpio-custom bus0=1,24,18,20,0,8000000,19 bus1=2,22,14,26,0,8000000,21
            /usr/bin/spirw 12 1
            if [[ "$?" == "1" ]]; then
	    	rmmod spi-gpio-custom
			insmod spi-gpio-custom bus0=1,24,18,20,0,8000000,19
                echo "LG08" > /var/iot/board
            else
                echo "LG08P" > /var/iot/board
            fi
        fi
    fi

    board=`cat /var/iot/board`
	model=$board

    uci set gateway.general.model="$board"

    uci commit system
    uci commit gateway

    DEB=`uci get gateway.general.DEB`
    if [[ "$DEB" -gt 1 ]]; then
        DEB="1"
    fi

	# Detect Cellular USB device	(and repeat to be sure)
	cat /sys/kernel/debug/usb/devices | grep "Vendor=2c7c ProdID=0125" -c > /tmp/cell_detect.txt
	(sleep 30; cat /sys/kernel/debug/usb/devices | grep "Vendor=2c7c ProdID=0125" -c > /tmp/cell_detect.txt) &
	
	# Detect model
	is_lps8=$(hexdump -v -e '11/1 "%_p"' -s $((0x908)) -n 11 /dev/mtd6 | grep -c "lps8")
	is_dlos8=$(hexdump -v -e '11/1 "%_p"' -s $((0x908)) -n 11 /dev/mtd6 | grep -c "los8")
	
	EC25_P2="/dev/ttyUSB2"
	EC25_P3="/dev/ttyUSB3"
	if [ $board == "LG08" ] || [ $board == "LG08P" ];then
		model="LG308"
		if [ $is_lps8 == "1" ]; then
			model="LPS8"
		elif [ $is_dlos8 == "1" ]; then
			model="DLOS8"
			ln -s /dev/ttyUSB0 /dev/ttyGPS
			EC25_P2="/dev/ttyUSB3"
			EC25_P3="/dev/ttyUSB4"
		fi
	elif [ $board == "LG01" ];then
		model="LG01"
	elif [ $board == "LG02" ];then
		model="LG02"
	fi	
	
	[ "`uci get network.cellular.device`" != "$EC25_P2" ] && uci set network.cellular.device=$EC25_P2 && uci commit network
	#ln -s $EC25_P2 /dev/ttyModem;
	ln -s $EC25_P3 /dev/ttyModemAT


	case $model in
		LG01) pic="Dragino-LG01.png"
		;;
		LG02) pic="Dragino-LG02.png"
		;;
		LG308)	pic="Dragino-LG308.png"
		;;
		LPS8)	pic="Dragino-LPS8.png"
		;;
		DLOS8) pic="Dragino-DLOS8.png"
		;;
	esac
	echo $model > /tmp/iot/model.txt
	echo $pic   > /tmp/iot/pic.txt
}

stop() {
    exit 0
}

