#!/bin/sh /etc/rc.common

START=50
STOP=90

start() {

    [ ! -d /var ] && ln -sf /tmp /var
    [ -d /var ] && mkdir -p /var/iot/channels
    [ -d /var ] && mkdir -p /var/iot/receive
	[ -d /var ] && mkdir -p /var/iot/push
	
	EC25_P2="/dev/ttyUSB2"
	EC25_P3="/dev/ttyUSB3"

	SN=`hexdump -v -e '11/1 "%_p"' -s $((0x908)) -n 11 /dev/mtd6`
	case $SN in
	  *"ig16"*)
		logger "[Model Detected]: LIG16"
		chip="sx1302"
		board="LG08"
		model="LIG16"
		pic="Dragino-LIG16.png"
		;;
	  *"lps8"*)
		logger "[Model Detected]: LPS8"
		chip="sx1308"
		board="LG08"
		model="LPS8"
		pic="Dragino-LPS8.png"
		;;
	  *"los8"*)
		logger "[Model Detected]: DLOS8"
		chip="sx1301"
		board="LG08"
		model="DLOS8"
		pic="Dragino-DLOS8.png"
		ln -s /dev/ttyUSB0 /dev/ttyGPS
		EC25_P2="/dev/ttyUSB3"
		EC25_P3="/dev/ttyUSB4"
		;;
	  *)
		logger "[Model Detected]: LIG16"
		chip="sx1302"
		board="LG08"
		model="LIG16"
		pic="Dragino-LIG16.png"
        ;;

	esac

	[ -d /var/iot ] && echo $chip > /var/iot/chip
	[ -d /var/iot ] && echo $model > /var/iot/model.txt
	[ -d /var/iot ] && echo $pic   > /var/iot/pic.txt
	[ -d /var/iot ] && echo $board > /var/iot/board

	uci set gateway.general.model="$board"
	uci commit system
	uci commit gateway

    DEB=`uci get gateway.general.DEB`
    if [[ "$DEB" -gt 1 ]]; then
        DEB="1"
    fi
	
	# Detect Cellular USB device	(and repeat to be sure)
	cat /sys/kernel/debug/usb/devices | grep "Vendor=2c7c ProdID=0125" -c > /tmp/cell_detect.txt
	(sleep 3; cat /sys/kernel/debug/usb/devices | grep "Vendor=2c7c ProdID=0125" -c > /tmp/cell_detect.txt) &
	
	[ "`uci get network.cellular.device`" != "$EC25_P2" ] && uci set network.cellular.device=$EC25_P2 && uci commit network
	#ln -s $EC25_P2 /dev/ttyModem;
	#ln -s $EC25_P3 /dev/ttyModemAT
}

stop() {
    exit 0
}

