#!/bin/sh /etc/rc.common

START=55
USE_PROCD=1

	chip=`cat /var/iot/chip`

init_board() {
	model=`cat /tmp/iot/model.txt`
    board=`cat /var/iot/board`

    mode=`uci get gateway.general.server_type`

    if [[ "$chip" = "sx1276_2" ]]; then
        process="lg02_pkt_fwd"
    elif [[ "$chip" = "sx1276_1" ]]; then
        process="lg01_pkt_fwd"
    elif [[ "$chip" = "sx1301" ]] || [[ "$chip" = "sx1308" ]] ; then
        process="lora_pkt_fwd"
#        /usr/bin/reset_lgw.sh start
        /usr/bin/generate-config.sh
    elif [[ "$chip" = "sx1302" ]]; then
        process="fwd"
	ln -sf /usr/bin/fwd_sx1302 /usr/bin/fwd
	/usr/bin/generate-config.sh
    else
        exit 1
    fi

    if [[ "$mode" = "disabled" ]] || [[ "$mode" = "loriot" ]] || [[ "$mode" = "station" ]] ; then
        process_running=`pidof $process`
        if [[ ! -z "process_running" ]]; then
            stop
        fi
        exit 0
    fi

    DEB=`uci get gateway.general.DEB`
    if [[ "$DEB" -gt 1 ]]; then
        DEB="1"
    fi
	
    #	ps | grep "iot_keep_alive" | grep -v grep | awk '{print $1}' | xargs kill -s 9
    #	/usr/bin/iot_keep_alive.sh &
	
}

start_service() {
    init_board
    procd_open_instance
    procd_set_param command /usr/bin/"$process"
	if [[ "$chip" = "sx1302" ]]; then
		procd_append_param command -d sx1302
	fi
    procd_set_param file  /etc/config/gateway
    procd_set_param stdout "$DEB"
    procd_set_param respawn 360 5 0
    procd_set_param pidfile /var/run/"$process".pid
    procd_close_instance
}

reload_service() {
    stop
    start
}

service_triggers()
{
    procd_add_reload_trigger "network" "wireless" "gateway" "mqtt" "tcp_client"
    for iface in `cat /etc/config/network | grep interface | awk -F "\'"  '{print $2}'`; do
        procd_add_interface_trigger "interface.*.up" "$iface" /etc/init.d/lora_gw reload
    done
}
