				<option value="us-2.lns.mydevices.com" >United States (us-2.lns.mydevices.com)</option>
				<option value="eu-2.lns.mydevices.com" >Europe (eu-2.lns.mydevices.com)</option>
				<option value="au-2.lns.mydevices.com" >Australia (au-2.lns.mydevices.com)</option>
				<option value="as-2.lns.mydevices.com" >Asia (as-2.lns.mydevices.com)</option>
				<option value="in-2.lns.mydevices.com" >India (in-2.lns.mydevices.com)</option>
				<option value="jp-2.lns.mydevices.com" >Japan (jp-2.lns.mydevices.com)</option>