				<option value="us-1.lns.mydevices.com" >United States (us-1.lns.mydevices.com)</option>
				<option value="eu-1.lns.mydevices.com" >Europe (eu-1.lns.mydevices.com)</option>
				<option value="au-1.lns.mydevices.com" >Australia (au-1.lns.mydevices.com)</option>
				<option value="jp-1.lns.mydevices.com" >Japan (jp-1.lns.mydevices.com)</option>
				<option value="cn-1.lns.mydevices.com" >China (cn-1.lns.mydevices.com)</option>
				<option value="kr-1.lns.mydevices.com" >Korea (kr-1.lns.mydevices.com)</option>