			  <option value="1" >1: US915 , FSB1 (902.3~903.7) </option>
			  <option value="2" >2: US915 , FSB2 (903.9~905.3) </option> 
			  <option value="3" >3: US915 , FSB3 (905.5~906.9) </option>
			  <option value="4" >4: US915 , FSB4 (907.1~908.5) </option>
			  <option value="5" >5: US915 , FSB5 (908.7~910.1) </option>
			  <option value="6" >6: US915 , FSB6 (910.3~911.7) </option>
			  <option value="7" >7: US915 , FSB7 (911.9~913.3) </option>
			  <option value="8" >8: US915 , FSB8 (913.5~914.9) </option>	 

