			  <option value="1" >1: AU915 , FSB1 (915.2~916.6) </option>
			  <option value="2" >2: AU915 , FSB2 (916.8~918.2) </option> 
			  <option value="3" >3: AU915 , FSB3 (918.4~919.8) </option>
			  <option value="4" >4: AU915 , FSB4 (920.0~921.4) </option>
			  <option value="5" >5: AU915 , FSB5 (921.6~923.0) </option>
			  <option value="6" >6: AU915 , FSB6 (923.2~924.6) </option>
			  <option value="7" >7: AU915 , FSB7 (924.8~926.2) </option>
			  <option value="8" >8: AU915 , FSB8 (926.4~927.8) </option>	 

