#!/bin/sh /etc/rc.common
# Copyright (c) 2015 Edwin Chen <edwin@dragino.com>

START=98

start()
{
    stop_lg02
    sleep 1
    start_lg02
}

stop() {
    stop_lg02
}

restart() {
    stop_lg02
    sleep 1
    start_lg02
}

start_lg02() {
    /usr/bin/lg02_pkt_fwd 
}

stop_lg02() {
    lorapid=`ps w| grep lg02_pkt_fwd | grep -v grep | awk '{print $1}'`
	if [[ ! -z "$lorapid" ]]; then 
		killall lg02_pkt_fwd
	fi
}
