#!/bin/sh /etc/rc.common
# Copyright (c) 2015 Edwin Chen <edwin@dragino.com>

START=98

start()
{
    stop_lg08
    sleep 1
    reset_pin
    start_lg08
}

stop() {
    stop_lg08
}

restart() {
    stop_lg08
    sleep 1
    reset_pin
    start_lg08
}

reset_pin() {
    /usr/bin/reset_lgw.sh stop
    /usr/bin/reset_lgw.sh start
}

start_lg08() {
    /usr/bin/lora_pkt_fwd 2>&1 > /var/log/gw_debug.log & 
}

stop_lg08() {
    lorapid=`ps w| grep lora_pkt_fwd | grep -v grep | awk '{print $1}'`
	if [[ ! -z "$lorapid" ]]; then 
		killall lora_pkt_fwd
	fi
}
