#!/bin/sh /etc/rc.common
# Copyright (c) 2015 Edwin Chen <edwin@dragino.com>

START=100
LORAMODE=`uci get lorawan.general.server_type`
LORALOG=`uci get lorawan.general.pfwd_debug`

start()
{
	start_pkt_fwd
}

restart() {
    stop_pkt_fwd
	start_pkt_fwd
}

stop() {
    stop_pkt_fwd
}

stop_pkt_fwd() {
	lorapid=`ps w| grep lg01_pkt_fwd | grep -v grep | awk '{print $1}'`
	if [[ ! -z $lorapid ]]; then 
		kill -9 $lorapid
	fi
}


start_pkt_fwd() {

	if [ $LORAMODE = "LoraWAN" ]; then
	    if [ $LORALOG = "1" ]; then
		    /usr/bin/lg01_pkt_fwd 2>&1 > /var/iot/log &
        else
		    /usr/bin/lg01_pkt_fwd 2>&1 > /dev/null &
        fi
    fi
}
